### ISSUE TITLE
Update RobotMap Configuration

### ISSUE THREAD

**Issue by MattMoradi** [echsRoboRaiders/RoboRaiders2018#2]
The RobotMap class will need to be updated according to the TalonSRX numbering on the robot. Please get this information from electrical and then update these numberings in the RobotMap. If there are subsystems which are added onto the bot such as arms or climbers, their configuration numberings will need to be added as well. This is what tells the RoboRIO where all the systems are located and which is which.

**Comment by hudson1740** [comment]
I have updated the RobotMap to the numbers given to me
